import { ArrowUpRight } from 'lucide-react';
import type { Language } from '../experiments/catalog';
import { evidence } from '../experiments/evidence';
export function FieldNotes({ language }: { language: Language }) {
  const t = (en: string, tr: string) => language === 'en' ? en : tr;
  return <div className="field-notes">
    <p className="notes-lead">{t('A model of communication, not a biological prediction.', 'İletişimi araştıran bir model; biyolojik tahmin aracı değildir.')}</p>
    <dl className="evidence-labels">
      <div><dt>{t('Observed biology', 'Gözlenen biyoloji')}</dt><dd>{t('Apis mellifera foragers can transfer food-location information through waggle dances. Recruitment and abandonment help shape allocation.', 'Apis mellifera toplayıcıları sallanma dansıyla besinin konum bilgisini aktarabilir. Katılım ve terk etme kaynak dağılımını etkiler.')}</dd></div>
      <div><dt>{t('Model abstraction', 'Model soyutlaması')}</dt><dd>{t('Private resource memories, expiring local dances and probabilistic followers. Scouts search independently; no bee can read colony metrics.', 'Bireysel kaynak hafızası, süreli yerel danslar ve olasılıksal katılım. Keşifçiler bağımsız arar; arılar koloni ölçümlerine erişemez.')}</dd></div>
      <div><dt>{t('Simulation assumption', 'Simülasyon varsayımı')}</dt><dd>{t('Constant flight speed, a fixed sensor radius, round patches, a configured scout trait and bounded angular/distance noise. Cargo is counted on arrival, followed by dancing or a fixed rest interval.', 'Sabit uçuş hızı ve algılama yarıçapı, dairesel kaynaklar, ayarlanmış keşifçi özelliği ve sınırlı açı/mesafe gürültüsü. Yük varışta sayılır; ardından dans veya sabit süreli dinlenme gelir.')}</dd></div>
      <div><dt>{t('Educational simplification', 'Eğitsel basitleştirme')}</dt><dd>{t('One tick is 0.1 model seconds. Distance, nectar and energy are abstract units. There is no sun compass, odor, brood, metabolism or temperature regulation.', 'Bir tick, 0,1 model saniyesidir. Mesafe, nektar ve enerji soyut birimlerdir. Güneş pusulası, koku, yavru, metabolizma ve sıcaklık düzenleme yoktur.')}</dd></div>
    </dl>
    <h3>{t('What the numbers mean', 'Sayılar ne anlama geliyor?')}</h3>
    <table className="definitions"><thead><tr><th>{t('Measure', 'Ölçüm')}</th><th>{t('Definition & limit', 'Tanım ve sınır')}</th></tr></thead><tbody>
      <tr><th>{t('Food collected', 'Toplanan besin')}</th><td>{t('Sum of cargo × sampled quality delivered to the hive. Model reward units, not grams.', 'Kovana getirilen yük × örneklenen kalite toplamı. Gram değil, model ödül birimi.')}</td></tr>
      <tr><th>{t('Throughput', 'Besin akışı')}</th><td>{t('Delivered reward during the last 600 ticks ÷ elapsed model minutes (up to 1 min). Startup uses the available elapsed window.', 'Son 600 tick içinde getirilen ödül ÷ geçen model dakikası (en fazla 1 dk). Başlangıçta mevcut süre kullanılır.')}</td></tr>
      <tr><th>{t('Allocation', 'Dağılım')}</th><td>{t('Bees flying to, foraging at, or returning from a known patch ÷ all such bees. Excludes searching and hive activity; not a share of the whole colony.', 'Bilinen kaynağa uçan, orada toplayan veya kaynaktan dönen arılar ÷ bu durumdaki tüm arılar. Arama ve kovan içi etkinlik hariç; tüm koloninin oranı değildir.')}</td></tr>
      <tr><th>{t('Recruited foragers', 'Katılan toplayıcılar')}</th><td>{t('Bees currently outside after social recruitment; may include scouts. A later independent scouting trip clears this flag.', 'Sosyal katılım sonrası dışarıda olan arılar; keşifçileri de içerebilir. Sonraki bağımsız keşif seferi bu işareti temizler.')}</td></tr>
      <tr><th>{t('Utility', 'Fayda')}</th><td><code>reward / (1 + 0.0015 × 2 × distance)</code><p>{t('A model assumption computed from that bee’s own visit.', 'Arının kendi ziyaretinden hesaplanan model varsayımı.')}</p></td></tr>
      <tr><th>{t('Recruitment probability', 'Katılım olasılığı')}</th><td><code>min(0.95, strength × utility × confidence)</code><p>{t('Per completed local dance observation. It is not an empirical probability.', 'Tamamlanan her yerel dans gözlemi için. Ampirik olasılık değildir.')}</p></td></tr>
    </tbody></table>
    <h3>{t('Evidence, with boundaries', 'Dayanaklar ve sınırları')}</h3>
    {evidence.map(paper => <article className="paper" key={paper.id}><span className="mono">{paper.year}</span><a href={paper.url} target="_blank" rel="noreferrer">{paper.title}<ArrowUpRight size={15} /></a><p>{paper.note[language]}</p></article>)}
    <h3>{t('Reproducibility', 'Tekrarlanabilirlik')}</h3>
    <p>{t('JSON exports include seed, all model versions, initial parameters and ordered tick-stamped interventions. Import recomputes the state from tick zero and pauses. Tick limits: 36,000; imports: 2 MB, 200 interventions and 36 million agent-ticks. Floating-point identity is tested within the same runtime; future engines are not guaranteed bitwise identical.', 'JSON dışa aktarımları seed, model sürümleri, başlangıç parametreleri ve sıralı, tick damgalı müdahaleleri içerir. İçe aktarım durumu sıfırdan hesaplar ve duraklatır. Sınırlar: 36.000 tick; içe aktarımda 2 MB, 200 müdahale ve 36 milyon arı-tick. Aynı çalışma ortamında eşitlik testlidir; gelecekteki motorlarda bit düzeyinde eşitlik garanti edilmez.')}</p>
    <p>{t('The communication view shows up to 30 model seconds of recent recruitment from a journal limited to 250 events. Dots on the outer ring represent participants now outside the hive. Contour lines and flower illustrations are visual context; patch circles define the resource extent, with a 28-unit sensor margin.', 'İletişim görünümü 250 olayla sınırlı günlükten en fazla 30 model saniyelik son katılımları gösterir. Dış halkadaki noktalar artık kovan dışında olan katılımcılardır. Eş yükselti çizgileri ve çiçekler görsel bağlamdır; kaynak dairelerinin çevresinde 28 birimlik algılama payı vardır.')}</p>
    <div className="ecosystem-links"><a href="https://swi.aserdargun.com" target="_blank" rel="noreferrer">SWI · {t('Swarm intelligence', 'Sürü zekâsı')}<ArrowUpRight size={14} /></a><a href="https://ant.aserdargun.com" target="_blank" rel="noreferrer">ANT · {t('Environmental traces', 'Çevresel izler')}<ArrowUpRight size={14} /></a></div>
  </div>;
}
